theme: jekyll-theme-minimal
title: Nick Duckwiler
name: Nick Duckwiler
description: Nick is an IT consultant at EY, managing large-scale project complexity for his clients. He is currently working with a national insurance provider to coordinate engineering, marketing, and operations teams in a firm-wide product transformation.

Inside and outside of his professional work, Nick uses data, code, and interactive design to convey information.
