theme: jekyll-theme-minimal
title: Nick Duckwiler
name: Nick Duckwiler
description: |
  Nick is a self-taught programmer, educator, and artist. He is a curriculum developer at Codecademy(https://www.codecademy.com), where he's written courses on [test-driven development](https://www.codecademy.com/pro/intensive/test-driven-development), Mongoose, Express, JavaScript, and [SQL](https://www.codecademy.com/pro/intensive/learn-sql-from-scratch). He's also worked as an IT consultant at EY. He draws, plays music, and designs interactive and gaming experiences - check out some of the pieces here.
